<?php

namespace Autumn\Janken\Domain;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-22 at 00:34:51.
 */
class PlayerTest extends \PHPUnit_Framework_TestCase {

	/**
	 * @var Player
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
//		$this->object = new Player;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers Autumn\Janken\Domain\Player::showHand()
	 */
	public function testShowHand() {
		$this->object = new Player("player 1");
		$expected = Player::STONE;
		$result = $this->object->showHand();
		$this->assertEquals($expected, $result);
	}

	/**
	 * @covers Autumn\Janken\Domain\Player::__toString
	 */
	public function test__toString() {
		$this->object = new Player("player 1");
		$expected = "[player 1]";
		$result = '' . $this->object;
		$this->assertEquals($expected, $result);
	}

}
